services:
  hackathon.healthmed.api:
    image: "${DOCKER_REGISTRY-}hackathonhealthmedapi"
    build:
      context: .
      dockerfile: Hackathon.HealthMed.API/Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=hackathon.healthmed.db;Port=5432;Database=HealthMedDb;Username=postgres;Password=postgres
      - ConnectionStrings__RedisConnection=hackathon.healthmed.redis:6379
    depends_on:
      - hackathon.healthmed.db
      - hackathon.healthmed.redis

  hackathon.healthmed.db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: HealthMedDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hackathon.healthmed.redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
